---
abstract: 'A JIRA REST Client for automated scripts'
author:
  - 'Michael Friedman <frimicc@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JIRA-Client-Automated
provides:
  JIRA::Client::Automated:
    file: lib/JIRA/Client/Automated.pm
    version: 1.02
requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 1.02
